# Generated by Django 4.1.1 on 2022-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
